### ISSUE TITLE
bug(latching): latching mechanic not working

### ISSUE THREAD

**Issue by Mxrxk** [sufst/pcb#47]
### Description
The design using the D-type flip flops U1 seems to not be working. The potential culprits could be the power on state (POR) or the method in which U1 is wired.

A redesign is required.

### Steps To Reproduce
1. Connect power into the circuit using 12V supply
2. Connect the IMD_Ok signal into the board (J2 pin 2) and connect to 10V supply
3. Connect the IMD_OK_LATCHED signal to an oscilloscope (J3 pin 2)
4. Power on 12V and 10V simultaneously. You will notice that the latching will latch into the fault state (J3 pin 2 LOW). This issue persists even if the IMD_Ok signal is connected to the 12V supply to have a truly simultaneous connection in. 
5. Power on 10V slightly earlier than 12V. You will notice that the latching will now latch in the no-fault state (J3 pin 2 HIGH). However when IMD_Ok signal is sent to the fault state, the circuit remains latched in the no-fault state.

### Environment
B16 tools and equipment

### Expected Behaviour
When turned on simultaneously, the circuit should boot up in a no-fault state given that no faults are detected. If a fault is detected, the circuit must latch in the fault state and remain latched even if the IMD_Ok state changes to the no fault state. Power cycling the circuit should remove the error given that the signal is in a no-fault state.

**Comment by t-bre** [comment]
Maybe working, latch IC tested in isolation and behaves as expected. Requires further testing!

**Comment by t-bre** [comment]
See #68 which was probably the cause of this.
