### ISSUE TITLE
bug(tsal): fp-lib-table contains user-specific paths

### ISSUE THREAD

**Issue by t-bre** [sufst/pcb#7]
### Description
fp-lib-table for TSAL contains:

```text
(fp_lib_table
  (lib (name "footprints")(type "KiCad")(uri "/home/joe/pro/sufst/precharge/hardware/precharge/footprints.pretty")(options "")(descr ""))
)
```

This should be a path relative to the project, instead of an absolute path specific to one user. 

Not sure if this breaks the PCB in some way?

### Steps To Reproduce
1. Look at contents of `tsal/fp-lib-table`.
2. Single entry in table with path specific to one user.

### Expected Behaviour
No absolute paths in table.

**Comment by Mxrxk** [comment]
This doesn't break the PCB, I checked the issue and imported the footprints library correctly so the path should be relative for everyone now. That path should have been removed in the latest tsal feat.
